### ISSUE TITLE
XMLSyntaxError when I press `S` to save

### ISSUE THREAD

**Issue by darrenburns** [P403n1x87/austin-tui#20]
### Description

Hi, thanks for your work on Austin! I'm running it on some repos now and it's been enlightening

I'm getting an `XMLSyntaxError` when I press `S` to save results.

### Steps to Reproduce

I'm running `sudo austin-tui python -m rich` inside the repo https://github.com/Textualize/rich (on `master` branch), and get the following error when I press the `S` key to save the data:

```
Traceback (most recent call last):
  File "/Users/darrenburns/.local/bin/austin-tui", line 8, in <module>
    sys.exit(main())
  File "/Users/darrenburns/.local/pipx/venvs/austin-tui/lib/python3.10/site-packages/austin_tui/__main__.py", line 179, in main
    tui.run()
  File "/Users/darrenburns/.local/pipx/venvs/austin-tui/lib/python3.10/site-packages/austin_tui/__main__.py", line 144, in run
    self._view.close()
  File "/Users/darrenburns/.local/pipx/venvs/austin-tui/lib/python3.10/site-packages/austin_tui/view/__init__.py", line 238, in close
    task.result()
  File "/Users/darrenburns/.local/pipx/venvs/austin-tui/lib/python3.10/site-packages/austin_tui/view/__init__.py", line 163, in _input_loop
    self.on_exception(exc)
  File "/Users/darrenburns/.local/pipx/venvs/austin-tui/lib/python3.10/site-packages/austin_tui/view/austin.py", line 64, in on_exception
    self.callback(self.Event.EXCEPTION, exc)
  File "/Users/darrenburns/.local/pipx/venvs/austin-tui/lib/python3.10/site-packages/austin_tui/__main__.py", line 119, in on_view_event
    {
  File "/Users/darrenburns/.local/pipx/venvs/austin-tui/lib/python3.10/site-packages/austin_tui/__main__.py", line 168, in on_exception
    raise exc
  File "/Users/darrenburns/.local/pipx/venvs/austin-tui/lib/python3.10/site-packages/austin_tui/view/__init__.py", line 161, in _input_loop
    task.result()
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/darrenburns/.local/pipx/venvs/austin-tui/lib/python3.10/site-packages/austin_tui/controller.py", line 225, in _dump_stats
    self.view.markup(f"Stats saved as <running>{filename}</running> 📝 ")
  File "/Users/darrenburns/.local/pipx/venvs/austin-tui/lib/python3.10/site-packages/austin_tui/view/__init__.py", line 187, in markup
    return markup(str(text), self.palette)
  File "/Users/darrenburns/.local/pipx/venvs/austin-tui/lib/python3.10/site-packages/austin_tui/widgets/markup.py", line 162, in markup
    root = etree.fromstring(f"<amRoot>{text}</amRoot>")
  File "src/lxml/etree.pyx", line 3252, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1913, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1793, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1082, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Char 0x0 out of allowed range, line 1, column 2
```

**Expected behavior:** Data file to be saved to my filesystem

**Actual behavior:** Crash, with the exception above

**Reproduces how often:** 100% of the time

### Versions

* austin 3.3.0
* MacOS Monterrey 12.1 on M1 Macbook Pro

**Comment by P403n1x87** [comment]
This seems to be an issue with the lxml library on macOS, probably caused by the emoji in the string https://gist.github.com/karlcow/5c11c06fb0345ea02ad51e5f7e9a2d9f. Would you be able to try installing a more recent version of the library, or remove the emoji in "/Users/darrenburns/.local/pipx/venvs/austin-tui/lib/python3.10/site-packages/austin_tui/controller.py", line 225, to confirm? Cheers!

**Comment by wgordon17** [comment]
@P403n1x87 confirming that I had this issue as well on MacOS. Removing the emoji on line 261 in version 1.2.0 solved the issue for me.

Could you consider perhaps just removing the emoji? 🙏

**Comment by P403n1x87** [comment]
@wgordon17 thanks for confirming that removing the emoji works. It feels a bit anachronistic to remove emojis these days but if that solves it then I'll make the change!

**Comment by wgordon17** [comment]
It's really unfortunate that MacOS can't "just handle it", but here we are ¯\_(ツ)_/¯

**Comment by wgordon17** [comment]
Thanks for this, much appreciated! 🙏

**Comment by P403n1x87** [comment]
No worries. The release job is currently failing and it might take me a while before I can have a look at it. Meanwhile installing directly from GitHub should just work 🤞
